For this problem, the function for females is l<sub>x</sub> = 1000(1 - <sup>x</sup>/<sub>105</sub>) for 0 ≤ x ≤ 105, and the function for males is l<sub>x</sub> = 1000(1 - <sup>x</sup>/<sub>99</sub>) for 0 ≤ x ≤ 99. 

- Calculate the present value of whole life insurance policy starting at age x
- parameters for face value, current age (x) , gender (M/F), interest rate effective annual (i)
- first payment made at age x

In [91]:
# Shawdi Keshavarz
def prob1(p:int, x:int, gen:str, i:float):
    den = 0
    if gen == "M":
        den = 99
        # Shawdi Keshavarz
    elif gen == "F":
        den = 105
    else:
        den = 115
        
    n = den-x
    v = 1 / (1 + i)
        # Shawdi Keshavarz
    numer = 1 - (v**n)
    denom = 1 - v
    answer = (p/n)*v*(numer/denom)
    # Shawdi Keshavarz
    answer = '${:,.2f}'.format(answer)
    print(answer)
    
    
prob1(100000,50,'F', .08) # should equal 22,397.48 - example 9.2 from book
prob1(100000,40,'',.13) # should equal 10,255.34 - 9.1.b - added just for purpose of checking

$22,397.48
$10,255.34

- create additional columns in the data file to calculate D<sub>x</sub>, N<sub>x+t</sub>, M<sub>x</sub> and PV of future benefits under different interest rates
- all employees have policies that are not deferred
- pv of fututre benefits calculates as of current age
- i = .055, .075, .085, .095, .105, .125
- correctly calculate pv of any n year endowment insurance policies

In [92]:
# Shawdi Keshavarz
import pandas as pd
import numpy as np
life_table = pd.read_csv('STAT470_Life_Table.csv')
life_table['lx'] = life_table['lx'].str.replace(' ', '')
life_table['lx'] = life_table['lx'].str.replace(',', '')
life_table['lx'] = life_table['lx'].astype(int)

employee = pd.read_excel('STAT470_Employee_Data_2.xlsx')

d_values = [.055/1.055, .075/1.075, .085/1.085, .095/1.095, .105/1.105, .125/1.125]

# Dx's
life_table['Dx .055'] = life_table['Age'].apply(lambda x: ((1/1.055)**x)*(life_table.iloc[x,1]))
life_table['Dx .075'] = life_table['Age'].apply(lambda x: ((1/1.075)**x)*(life_table.iloc[x,1]))
life_table['Dx .085'] = life_table['Age'].apply(lambda x: ((1/1.085)**x)*(life_table.iloc[x,1]))
# Shawdi Keshavarz
life_table['Dx .095'] = life_table['Age'].apply(lambda x: ((1/1.095)**x)*(life_table.iloc[x,1]))
life_table['Dx .105'] = life_table['Age'].apply(lambda x: ((1/1.105)**x)*(life_table.iloc[x,1]))
life_table['Dx .125'] = life_table['Age'].apply(lambda x: ((1/1.125)**x)*(life_table.iloc[x,1]))

# Nx's
life_table['Nx .055'] = life_table['Age'].apply(lambda x: (life_table['Dx .055'].iloc[x:101]).sum())
life_table['Nx .075'] = life_table['Age'].apply(lambda x: (life_table['Dx .075'].iloc[x:101]).sum())
life_table['Nx .085'] = life_table['Age'].apply(lambda x: (life_table['Dx .085'].iloc[x:101]).sum())
life_table['Nx .095'] = life_table['Age'].apply(lambda x: (life_table['Dx .095'].iloc[x:101]).sum())
# Shawdi Keshavarz
life_table['Nx .105'] = life_table['Age'].apply(lambda x: (life_table['Dx .105'].iloc[x:101]).sum())
life_table['Nx .125'] = life_table['Age'].apply(lambda x: (life_table['Dx .125'].iloc[x:101]).sum())


# Mx's
life_table['Mx .055'] = life_table['Dx .055'] - (d_values[0]*life_table['Nx .055'])
# Shawdi Keshavarz
life_table['Mx .075'] = life_table['Dx .075'] - (d_values[1]*life_table['Nx .075'])
life_table['Mx .085'] = life_table['Dx .085'] - (d_values[2]*life_table['Nx .085'])
life_table['Mx .095'] = life_table['Dx .095'] - (d_values[3]*life_table['Nx .095'])
life_table['Mx .105'] = life_table['Dx .105'] - (d_values[4]*life_table['Nx .105'])
life_table['Mx .125'] = life_table['Dx .125'] - (d_values[5]*life_table['Nx .125'])

pd.options.display.float_format = '{:.4f}'.format
life_table

,Age,lx,dx,Dx .055,Dx .075,Dx .085,Dx .095,Dx .105,Dx .125,Nx .055,Nx .075,Nx .085,Nx .095,Nx .105,Nx .125,Mx .055,Mx .075,Mx .085,Mx .095,Mx .105,Mx .125
0,0,100000,723,100000.0000,100000.0000,100000.0000,100000.0000,100000.0000,100000.0000,1854327.4405,1408094.7037,1258151.1780,1138397.5509,1040753.7320,891436.2091,3328.9012,1760.8346,1435.1612,1234.9157,1104.8490,951.5323
1,1,99277,55,94101.4218,92350.6977,91499.5392,90663.9269,89843.4389,88246.2222,1754327.4405,1308094.7037,1158151.1780,1038397.5509,940753.7320,791436.2091,2643.5932,1088.2765,768.8017,574.6417,450.5504,308.8657
2,2,99223,36,89147.1440,85860.8978,84285.5019,82753.0702,81262.0544,78398.4198,1660226.0187,1215744.0061,1066651.6388,947733.6240,850910.2930,703189.9869,2595.0767,1041.5485,722.9311,529.6051,406.3252,266.1990
3,3,99187,29,84469.0045,79841.6240,77654.3056,75546.1606,73513.6389,69662.2003,1571078.8746,1129883.1083,982366.1369,864980.5538,769648.2386,624791.5671,2564.4186,1012.5699,694.7464,502.1856,379.6434,240.9150
4,4,99158,23,80041.9978,74249.5629,71549.8629,68971.7558,66508.7287,61903.8512,1486609.8701,1050041.4843,904711.8313,789434.3932,696134.5997,555129.3669,2541.0093,990.8547,673.8208,482.0139,360.1921,222.8105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,5339,"1,281",31.2769,5.1552,2.1194,0.8784,0.3670,0.0656,88.0025,14.1527,5.7494,2.3554,0.9729,0.1701,26.6891,4.1678,1.6689,0.6741,0.2746,0.0467
97,97,4058,"1,041",22.5332,3.6449,1.4847,0.6097,0.2524,0.0443,56.7256,8.9975,3.6301,1.4770,0.6059,0.1045,19.5760,3.0172,1.2003,0.4816,0.1949,0.0327
98,98,3017,823,15.8794,2.5208,1.0173,0.4140,0.1699,0.0293,34.1924,5.3526,2.1454,0.8672,0.3535,0.0602,14.0969,2.1474,0.8493,0.3388,0.1363,0.0226
99,99,2193,634,10.9407,1.7045,0.6815,0.2748,0.1117,0.0189,18.3130,2.8317,1.1281,0.4532,0.1836,0.0309,9.9860,1.5070,0.5932,0.2355,0.0943,0.0155
100,100,1559,"1,559",7.3723,1.1272,0.4466,0.1784,0.0719,0.0120,7.3723,1.1272,0.4466,0.1784,0.0719,0.0120,6.9879,1.0486,0.4116,0.1629,0.0651,0.0106

- create additional columns in the data file to calculate D<sub>x</sub>, N<sub>x+t</sub>, M<sub>x</sub> and PV of future benefits under different interest rates
- all employees have policies that are not deferred
- pv of fututre benefits calculates as of current age
- i = .055, .075, .085, .095, .105, .125
- correctly calculate pv of any n year endowment insurance policies

In [93]:
v_values = [1/1.055, 1/1.075, 1/1.085, 1/1.095, 1/1.105, 1/1.125]

pd.set_option('display.max_columns', 500)

# Dx's
employee['Dx - i=.055'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,3])
employee['Dx - i=.075'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,4])
# Shawdi Keshavarz
employee['Dx - i=.085'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,5])
employee['Dx - i=.095'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,6])
employee['Dx - i=.105'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,7])
employee['Dx - i=.125'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,8])


# N(x+t)'s
employee['N(x+t) - i=.055'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,9])
employee['N(x+t) - i=.075'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,10])
employee['N(x+t) - i=.085'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,11])
employee['N(x+t) - i=.095'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,12])
# Shawdi Keshavarz
employee['N(x+t) - i=.105'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,13])
employee['N(x+t) - i=.125'] = employee['Age at first annuity payment (x + t)'].apply(lambda x: life_table.iloc[x,14])


# Mx's
employee['Mx - i=.055'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,15])
employee['Mx - i=.075'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,16])
# Shawdi Keshavarz
employee['Mx - i=.085'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,17])
employee['Mx - i=.095'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,18])
employee['Mx - i=.105'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,19])
employee['Mx - i=.125'] = employee['Current Age (x)'].apply(lambda x: life_table.iloc[x,20])


# Pv's
# life annuity
employee['Pv la - i=.055'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.055']) / employee['Dx - i=.055']
employee['Pv la - i=.075'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.075']) / employee['Dx - i=.075']
employee['Pv la - i=.085'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.085']) / employee['Dx - i=.085']
employee['Pv la - i=.095'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.095']) / employee['Dx - i=.095']
employee['Pv la - i=.105'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.105']) / employee['Dx - i=.105']
# Shawdi Keshavarz
employee['Pv la - i=.125'] = (employee['Annual annuity payment'] * employee['N(x+t) - i=.125']) / employee['Dx - i=.125']

# life insurance
employee['Pv li - i=.055'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.055'])/employee['Dx - i=.055']
employee['Pv li - i=.075'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.075'])/employee['Dx - i=.075']
employee['Pv li - i=.085'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.085'])/employee['Dx - i=.085']
# Shawdi Keshavarz
employee['Pv li - i=.095'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.095'])/employee['Dx - i=.095']
employee['Pv li - i=.105'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.105'])/employee['Dx - i=.105']
employee['Pv li - i=.125'] = (employee['Face Value of Life Ins'] * employee['Mx - i=.125'])/employee['Dx - i=.125']

# n year endowment life insurance
employee.at[15,'Pv li - i=.055'] = (employee.iloc[15,6] * (life_table.iloc[62,15] - life_table.iloc[87,15] + life_table.iloc[87,3]))/life_table.iloc[62,3]
employee.at[15,'Pv li - i=.075'] = (employee.iloc[15,6] * (life_table.iloc[62,16] - life_table.iloc[87,16] + life_table.iloc[87,4]))/life_table.iloc[62,4]
# Shawdi Keshavarz
employee.at[15,'Pv li - i=.085'] = (employee.iloc[15,6] * (life_table.iloc[62,17] - life_table.iloc[87,17] + life_table.iloc[87,5]))/life_table.iloc[62,5]
employee.at[15,'Pv li - i=.095'] = (employee.iloc[15,6] * (life_table.iloc[62,18] - life_table.iloc[87,18] + life_table.iloc[87,6]))/life_table.iloc[62,6]
employee.at[15,'Pv li - i=.105'] = (employee.iloc[15,6] * (life_table.iloc[62,19] - life_table.iloc[87,19] + life_table.iloc[87,7]))/life_table.iloc[62,7]
employee.at[15,'Pv li - i=.125'] = (employee.iloc[15,6] * (life_table.iloc[62,20] - life_table.iloc[87,20] + life_table.iloc[87,8]))/life_table.iloc[62,8]


employee.at[18,'Pv li - i=.055'] = (employee.iloc[18,6] * (life_table.iloc[70,15]-life_table.iloc[90,15] + life_table.iloc[90,3]))/life_table.iloc[70,3]
employee.at[18,'Pv li - i=.075'] = (employee.iloc[18,6] * (life_table.iloc[70,16]-life_table.iloc[90,16] + life_table.iloc[90,4]))/life_table.iloc[70,4]
employee.at[18,'Pv li - i=.085'] = (employee.iloc[18,6] * (life_table.iloc[70,17]-life_table.iloc[90,17] + life_table.iloc[90,5]))/life_table.iloc[70,5]
employee.at[18,'Pv li - i=.095'] = (employee.iloc[18,6] * (life_table.iloc[70,18]-life_table.iloc[90,18] + life_table.iloc[90,6]))/life_table.iloc[70,6]
# Shawdi Keshavarz
employee.at[18,'Pv li - i=.105'] = (employee.iloc[18,6] * (life_table.iloc[70,19]-life_table.iloc[90,19] + life_table.iloc[90,7]))/life_table.iloc[70,7]
employee.at[18,'Pv li - i=.125'] = (employee.iloc[18,6] * (life_table.iloc[70,20]-life_table.iloc[90,20] + life_table.iloc[90,8]))/life_table.iloc[70,8]


# total present value of future beneifts
employee['Pv i=.055'] = employee['Pv la - i=.055'] + employee['Pv li - i=.055']
employee['Pv i=.075'] = employee['Pv la - i=.075'] + employee['Pv li - i=.075']
employee['Pv i=.085'] = employee['Pv la - i=.085'] + employee['Pv li - i=.085']
# Shawdi Keshavarz
employee['Pv i=.095'] = employee['Pv la - i=.095'] + employee['Pv li - i=.095']
employee['Pv i=.105'] = employee['Pv la - i=.105'] + employee['Pv li - i=.105']
employee['Pv i=.125'] = employee['Pv la - i=.125'] + employee['Pv li - i=.125']


sum_row = employee.sum(axis=0)
sum_row[0:25] = np.nan
employee.loc[len(employee.index)] = sum_row
        # Shawdi Keshavarz
employee = employee.rename(index={20:"SUMS"})

# Shawdi Keshavarz
for x in employee:
    if '-' in x:
        employee[x] = round(employee[x],4)
    if 'Pv' in x:
        employee[x] = round(employee[x],2)
        employee[x] = (employee[x].apply('{:.2f}'.format))


employee

,EEID,Status,Current Age (x),Age at first annuity payment (x + t),Annual annuity payment,Life Ins. Policy Type,Face Value of Life Ins,Dx - i=.055,Dx - i=.075,Dx - i=.085,Dx - i=.095,Dx - i=.105,Dx - i=.125,N(x+t) - i=.055,N(x+t) - i=.075,N(x+t) - i=.085,N(x+t) - i=.095,N(x+t) - i=.105,N(x+t) - i=.125,Mx - i=.055,Mx - i=.075,Mx - i=.085,Mx - i=.095,Mx - i=.105,Mx - i=.125,Pv la - i=.055,Pv la - i=.075,Pv la - i=.085,Pv la - i=.095,Pv la - i=.105,Pv la - i=.125,Pv li - i=.055,Pv li - i=.075,Pv li - i=.085,Pv li - i=.095,Pv li - i=.105,Pv li - i=.125,Pv i=.055,Pv i=.075,Pv i=.085,Pv i=.095,Pv i=.105,Pv i=.125
0,1.0000,Active,28.0000,70.0000,19500.0000,Whole Life,100000.0000,21836.4061,12906.6352,9959.0374,7702.9077,5971.8137,3613.9272,16879.7098,4014.1499,1985.1298,990.4721,498.4450,129.3677,2056.6561,646.0150,380.5035,231.1935,144.5828,61.0098,15073.65,6064.78,3886.92,2507.39,1627.59,698.04,9418.47,5005.29,3820.69,3001.38,2421.09,1688.19,24492.12,11070.07,7707.61,5508.77,4048.68,2386.23
1,2.0000,Active,27.0000,70.0000,15000.0000,Whole Life,100000.0000,23060.4977,13888.5387,10816.3855,8443.1376,6605.4678,4069.7430,16879.7098,4014.1499,1985.1298,990.4721,498.4450,129.3677,2078.5417,658.9506,390.4849,238.9137,150.5681,64.6319,10979.63,4335.39,2752.95,1759.66,1131.89,476.82,9013.43,4744.56,3610.12,2829.68,2279.45,1588.11,19993.06,9079.96,6363.07,4589.34,3411.34,2064.92
2,3.0000,Active,38.0000,68.0000,22800.0000,Whole Life,100000.0000,12616.6149,6180.3728,4347.1664,3067.6075,2171.5496,1098.3493,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,1846.4468,533.7772,298.0433,170.3966,99.6030,36.1403,37555.46,18786.84,13411.75,9630.12,6952.96,3681.04,14635.04,8636.65,6856.04,5554.71,4586.72,3290.42,52190.50,27423.49,20267.78,15184.83,11539.68,6971.46
3,4.0000,Active,41.0000,67.0000,24600.0000,Whole Life,150000.0000,10682.6883,4946.3446,3383.8580,2323.0177,1600.2138,766.9693,22959.6285,5711.3886,2889.9396,1475.6515,760.1016,206.7541,1781.3560,503.0701,276.8399,155.7049,89.3886,31.1537,52871.23,28404.85,21009.31,15626.67,11685.00,6631.49,25012.75,15255.81,12271.79,10054.05,8379.07,6092.89,77883.98,43660.66,33281.09,25680.72,20064.07,12724.38
4,5.0000,Active,34.0000,68.0000,20400.0000,Whole Life,100000.0000,15725.9797,8304.5012,6061.6414,4437.3255,3257.4960,1770.1724,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,1930.4477,576.1106,328.2444,192.0116,115.1216,44.2134,26958.37,12509.80,8605.91,5956.70,4147.16,2043.58,12275.53,6937.33,5415.11,4327.19,3534.05,2497.69,39233.90,19447.13,14021.01,10283.89,7681.21,4541.27
5,6.0000,Active,53.0000,65.0000,31800.0000,Whole Life,150000.0000,5386.5206,1990.8571,1218.7442,749.4460,462.9008,178.8978,27810.2673,7129.6078,3663.4109,1899.8507,994.0264,279.0411,1478.7918,379.4066,197.1637,104.1102,55.8128,16.7282,164181.40,113881.37,95587.30,80613.21,68286.85,49600.98,41180.34,28586.18,24266.42,20837.44,18085.77,14026.03,205361.75,142467.55,119853.72,101450.65,86372.62,63627.00
6,7.0000,Active,39.0000,68.0000,23400.0000,Whole Life,100000.0000,11937.5618,5738.9370,3999.4638,2796.4748,1961.7006,974.5703,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,1825.1319,523.5301,290.9021,165.4034,96.1003,34.4001,40736.28,20764.34,14961.35,10841.80,7899.28,4257.74,15288.98,9122.42,7273.53,5914.71,4898.83,3529.78,56025.26,29886.76,22234.88,16756.52,12798.11,7787.51
7,8.0000,Active,51.0000,65.0000,30600.0000,Whole Life,150000.0000,6056.1464,2324.0214,1449.2896,907.7196,570.9468,228.7142,27810.2673,7129.6078,3663.4109,1899.8507,994.0264,279.0411,1534.8736,400.3284,210.0307,112.0591,60.7450,18.6518,140517.44,93874.35,77348.50,64045.58,53275.03,37333.30,38016.10,25838.51,21737.97,18517.68,15959.02,12232.57,178533.53,119712.86,99086.47,82563.26,69234.05,49565.87
8,9.0000,Active,44.0000,67.0000,26400.0000,Whole Life,150000.0000,9032.3832,3953.1032,2630.2807,1756.6666,1177.5256,534.8101,22959.6285,5711.3886,2889.9396,1475.6515,760.1016,206.7541,1712.7442,472.4757,256.2933,141.8550,80.0186,26.8191,67106.78,38142.35,29006.18,22176.78,17041.40,10206.07,28443.39,17928.03,14615.93,12112.85,10193.24,7522.04,95550.18,56070.39,43622.11,34289.63,27234.64,17728.11
9,10.0000,Active,30.0000,68.0000,18000.0000,Whole Life,100000.0000,19577.6392,11145.0028,8441.9342,6410.7750,4880.5163,2849.4329,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,2014.2089,621.6202,361.9379,217.0285,133.7485,54.6254,19107.03,8224.81,5452.39,3637.97,2442.37,1120.19,10288.31,5577.57,4287.38,3385.37,2740.46,1917.06,29395.35,13802.38,9739.78,7023.34,5182.83,3037.25
10,11.0000,Active,46.0000,67.0000,27600.0000,Whole Life,150000.0000,8068.3122,3400.9988,2221.4057,1456.6203,958.8067,420.1262,22959.6285,5711.3886,2889.9396,1475.6515,760.1016,206.7541,1664.6529,452.0145,242.8668,133.0103,74.1700,24.2330,78540.06,46349.42,35906.24,27960.60,21880.12,13582.62,30947.98,19935.96,16399.54,13697.15,11603.49,8652.03,109488.04,66285.38,52305.78,41657.76,33483.61,22234.65
11,12.0000,Active,34.0000,68.0000,20400.0000,Whole Life,100000.0000,15725.9797,8304.5012,6061.6414,4437.3255,3257.4960,1770.1724,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,1930.4477,576.1106,328.2444,192.0116,115.1216,44.2134,26958.37,12509.80,8605.91,5956.70,4147.16,2043.58,12275.53,6937.33,5415.11,4327.19,3534.05,2497.69,39233.90,19447.13,14021.01,10283.89,7681.21,4541.27
12,13.0000,Active,40.0000,67.0000,24000.0000,Whole Life,150000.0000,11293.4938,5328.2934,3679.0626,2548.9536,1771.8852,864.6211,22959.6285,5711.3886,2889.9396,1475.6515,760.1016,206.7541,1803.4012,513.2776,283.8229,160.4988,92.6909,32.7365,48791.91,25725.56,18852.23,13894.19,10295.50,5739.05,23952.75,14449.59,11571.82,9444.98,7846.80,5679.33,72744.65,40175.14,30424.05,23339.17,18142.30,11418.38
13,14.0000,Active,51.0000,65.0000,30600.0000,Whole Life,150000.0000,6056.1464,2324.0214,1449.2896,907.7196,570.9468,228.7142,27810.2673,7129.6078,3663.4109,1899.8507,994.0264,279.0411,1534.8736,400.3284,210.0307,112.0591,60.7450,18.6518,140517.44,93874.35,77348.50,64045.58,53275.03,37333.30,38016.10,25838.51,21737.97,18517.68,15959.02,12232.57,178533.53,119712.86,99086.47,82563.26,69234.05,49565.87
14,15.0000,Active,43.0000,67.0000,25800.0000,Whole Life,150000.0000,9553.7724,4260.5601,2861.2244,1928.5173,1304.5259,603.2151,22959.6285,5711.3886,2889.9396,1475.6515,760.1016,206.7541,1736.0695,482.6843,263.0857,146.3914,83.0595,28.2002,62002.57,34585.55,26058.93,19741.49,15032.76,8843.04,27257.34,16993.69,13792.30,11386.32,9550.54,7012.47,89259.91,51579.24,39851.23,31127.81,24583.30,15855.52
15,16.0000,Retiree,62.0000,62.0000,60450.0000,25-yr Endowment,200000.0000,3079.3620,961.1440,541.3392,306.5052,174.4424,57.3663,36460.6983,9781.9326,5144.3241,2731.1912,1463.1980,430.8096,1178.5673,278.6836,138.3276,69.5525,35.4055,9.4986,715748.66,615222.93,574453.87,538654.83,507046.03,453967.62,80910.52,61437.06,54093.52,47946.17,42771.80,34665.42,796659.18,676659.99,628547.39,586600.99,549817.83,488633.04
16,17.0000,Retiree,64.0000,64.0000,74800.0000,Whole Life,200000.0000,2690.8123,808.9080,447.2369,248.6207,138.9489,44.0838,30501.0796,7938.5158,4110.6478,2148.4714,1132.9752,323.1249,1100.7087,255.0580,125.2045,62.2236,31.2906,8.1811,847878.06,734077.30,687502.49,646389.02,609911.72,548267.66,81812.37,63062.31,55990.26,50055.05,45039.00,37115.97,929690.43,797139.61,743492.76,696444.07,654950.73,585383.63
17,18.0000,Retiree,68.0000,68.0000,65475.0000,Whole Life,200000.0000,2024.1723,564.4678,300.7409,161.1590,86.8520,25.6474,20781.7012,5092.5305,2557.1530,1295.6765,662.2235,177.3276,940.7661,209.1750,100.4110,48.7487,23.9258,5.9443,672216.44,590704.10,556723.68,526401.91,499229.56,452698.09,92953.16,74114.05,66775.72,60497.68,55095.52,46354.22,765169.60,664818.14,623499.40,586899.59,554325.08,499052.31
18,19.0000,Retiree,70.0000,70.0000,63540.0000,20-yr Endowment,250000.0000,1738.3254,466.8859,244.1865,128.4739,67.9898,19.3699,16879.7098,4014.1499,1985.1298,990.4721,498.4450,129.3677,858.3405,186.8289,88.6694,42.5425,20.6263,4.9957,616994.25,546298.55,516552.58,489862.91,465822.70,424371.53,128126.19,104144.65,94524.59,86160.78,78861.47,66844.57,745120.44,650443.20,611077.18,576023.69,544684.17,491216.10
19,20.0000,Retiree,75.0000,75.0000,58775.0000,Whole Life,250000.0000,1138.9939,278.4973,139.0675,69.8871,35.3415,9.2048,9451.3960,2085.9127,993.2005,476.9944,231.0010,55.4971,646.2671,132.9685,61.2591,28.5040,13.3912,3.0385,487716.22,440217.92,419762.91,401152.05,384168.32,354361.01,141850.43,119362.49,110124.83,101964.50,94727.00,82524.69,629566.65,559580.41,529887.75,503116.55,478895.32,436885.70
SUMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4272451.23,3484554.36,3193789.91,2950855.16,2745298.44,2417256.73,861674.72,633908.01,554580.61,490532.56,438066.40,357963.73,5134125.95,4118462.36,3748370.52,3441387.72,3183364.84,2775220.46